package Principal;


import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Reymundo Tenorio
 */
public class BuscarProducto extends javax.swing.JFrame {

    /**
     * Creates new form BuscarProducto
     */
    public BuscarProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridLayout(1, 3, 5, 0));

        jLabel1.setText("Buscar Por");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(jLabel1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ID", "Nombre" }));
        jPanel2.add(jComboBox1);

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        jPanel2.add(jTextField1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jButton1.setText("Nuevo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        jButton2.setText("Modificar");
        jPanel3.add(jButton2);

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents
public DefaultTableModel model = new DefaultTableModel();

    public DefaultTableModel getModel() {
        return model;
    }

    public void setModel(DefaultTableModel model) {
        this.model = model;
    }



ManagmentProducto ver = new ManagmentProducto();
ArrayList<Producto> Productos = ver.getProductos();
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened


//Productos=Productos=ver.getProductos();

  String header [] = {"ID","Nombre","Descripción","Cantidad","Costo"};
              



model.setColumnIdentifiers(header);

String Datos[] = new String[5];
              model.setNumRows(0);
              jTable1.setModel(model);

for( Producto s : Productos ){
  
    
              
              Datos[0]=String.valueOf(s.getID());
              Datos [1]=s.getNombre();
              Datos [2]=s.getDescripcion();
              Datos [3]=String.valueOf(s.getCantidad());
              Datos [4]=String.valueOf(s.getCosto());
            
              model.addRow(Datos);
               
                }     




// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
        NewProducto n = new NewProducto(this, true);
n.setTxtid(ver.Tamano()+1);
n.setVisible(true);
n.toFront();

if(n.getCr()!=null){
ver.Agregar(n.getCr());
}
String Datos[] = new String[5];
              model.setNumRows(0);
              jTable1.setModel(model);
 
for( Producto s : Productos ){
  
    
              
              Datos[0]=String.valueOf(s.getID());
              Datos [1]=s.getNombre();
              Datos [2]=s.getDescripcion();
              Datos [3]=String.valueOf(s.getCantidad());
              Datos [4]=String.valueOf(s.getCosto());
            
              model.addRow(Datos);
               
                }     





// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
int index = jComboBox1.getSelectedIndex();

switch(index){
    
    case 0: 
        for(int i=0; i<jTable1.getRowCount();i++){
          String obtn= (String) this.jTable1.getModel().getValueAt(0, 1);
          if(obtn == null ? jTextField1.getText() == null : obtn.equals(jTextField1.getText())){
              
              
          }
          }
        
        break;
    
    
    
}
// TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 
           int fila = jTable1.getSelectedRow();
        //     int columna = jTable1.columnAtPoint(evt.getPoint());

        int id = 0;
      String Nombre, Descripcion;
        int Unids;
        double Costo;
        
        Producto p = new Producto();
        System.out.println("filaa "+fila);
        
        if (fila > -1){
            // System.out.println(model.getValueAt(fila,columna));
            id= Integer.parseInt(this.jTable1.getModel().getValueAt(fila, 0).toString().trim());
            Nombre= (this.jTable1.getModel().getValueAt(fila, 1).toString().trim());
            Descripcion=(this.jTable1.getModel().getValueAt(fila, 2).toString().trim());
            Unids=Integer.parseInt(this.jTable1.getModel().getValueAt(fila, 3).toString().trim());
            Costo=Double.parseDouble(this.jTable1.getModel().getValueAt(fila, 4).toString().trim());
            
            p.setID(id);
            p.setNombre(Nombre);
            p.setDescripcion(Descripcion);
            p.setCantidad(Unids);
            p.setCosto(Costo);
            
            
              ver.Eliminar(id-1);
              
              String Datos[] = new String[5];
              model.setNumRows(0);
              jTable1.setModel(model);
 
for( Producto s : Productos ){
  
    
              
              Datos[0]=String.valueOf(s.getID());
              Datos [1]=s.getNombre();
              Datos [2]=s.getDescripcion();
              Datos [3]=String.valueOf(s.getCantidad());
              Datos [4]=String.valueOf(s.getCosto());
            
              model.addRow(Datos);
               
                }     


              
        }
        
//      int index =  Productos.indexOf(p);
//        System.out.println("incdex"+index);
        
      
//        System.out.println("Producto! id= "+p.getID());
//        System.out.println("Producto! name= "+p.getNombre());
//        System.out.println("Producto! desc= "+p.getDescripcion());
//        System.out.println("Producto! unids= "+p.getCantidad());
//        System.out.println("Producto! cost= "+p.getCosto());
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarProducto().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
